
version: 2

sources:
  - name: jaffle
    database: project-2132b8fa-c447-44ea-a20
    schema: Amazon
    tables:
      - name: raw_customers
      - name: raw_orders



models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null


  - name: customers
    columns:
      - name: id
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('orders')
              field: customer
      - name: name
        tests:
          - not_null
